### ISSUE TITLE
Localized country & capital names

### ISSUE THREAD

**Issue by oh-ren** [annexare/Countries#17]
Hey, pretty cool & handy library!

One thing missing is localized country & capital names.
I could provide a .json source file for Dutch. See below for example.
A lot of capital names are identical to the English one, but I think it would be best to explicitly write them down anyway.
Antarctica has no capital - you use an empty string value here, but wouldn't `null` be more correct?

Please let me know your thoughts, cheers!

`./data/i18n/nl/countries.json`
```js
{
  "AD": {
    "name": "Andorra",
    "capital": "Andorra la Vella"
  },
  "AE": {
    "name": "Verenigde Arabische Emiraten",
    "capital": "Abu Dhabi"
  },
  "AF": {
    "name": "Afghanistan",
    "capital": "Kabul"
  },
  "AG": {
    "name": "Antigua en Barbuda",
    "capital": "Saint John's"
  },
  "AI": {
    "name": "Anguilla",
    "capital": "The Valley"
  },
  "AL": {
    "name": "Albanië",
    "capital": "Tirana"
  },
  "AM": {
    "name": "Armenië",
    "capital": "Jerevan"
  },
  "AO": {
    "name": "Angola",
    "capital": "Luanda"
  },
  "AQ": {
    "name": "Antarctica",
    "capital": null
  },
  "AR": {
    "name": "Argentinië",
    "capital": "Buenos Aires"
  },
  "AS": {
    "name": "Amerikaans-Samoa",
    "capital": "Pago Pago"
   }
  ...
}
```

**Comment by z-ax** [comment]
Hi @oh-ren, thanks for suggestions!

To be honest, I don't see a reason to expand small library to the full scale - projects I've been working at, usually need exactly data stored here — for Country/Language/Continent select inputs/dropdowns/tags, to easily find own in English or local language with no keyboard switch. And then store in ISO code as well. As you probably seen already, the library is pretty small in size yet and I'd like to keep it that way (even if grown a bit with languages lists in v2).

In any case, by popular demand we could expand this with translations like you offer. It can be a separate NPM module even, as extension to current. But then I'll want a OSS community to support it because even if it could be translated via API, verification should be made by locals — let me know if it makes sense.

As for the values — empty strings are preferred to reduce code (`a.capital` looks better than `a.capital || ''` speaking of every field you may use). Empty string check is also a way to go if required.
