### ISSUE TITLE
3 countries no languages?

### ISSUE THREAD

**Issue by beastmst** [annexare/Countries#24]
found 3 countries language is empty

BV, AQ, MY

**Comment by z-ax** [comment]
Hi, thanks for the check! At the time they were added no locale was specified.

AQ is Antarctica, no countries = no locale.

Now as I checked:
* BV (Bouvet Island) Belongs to Norway, so will copy locale from there
* MY (Malaysia) has specified Malay (will add `ms`) and Wiki says English as recognizable - not sure if should add, but Malay is specified as macrolanguage that's why there is a doubt, for usability in applications maybe specifying English as well could be useful

**Comment by beastmst** [comment]
MY you can copy from singapore...
thanks

**Comment by z-ax** [comment]
Why Singapore?

**Comment by beastmst** [comment]
Cause official language is malay, english mostly use in the business world.. and 30% of the population is chinese... and 3% is indian, so malay, english, chinese and tamil are the languages we used here

thanks

**Comment by z-ax** [comment]
Well, the library is more about the official languages data.
But to be honest, I'm thinking for a while about "spokenLanguages" property so it could be used conveniently in applications.

**Comment by beastmst** [comment]
yes... maybe is a good idea...

**Comment by z-ax** [comment]
Published in `v2.3.2`.
